
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { GraphQlProviders } from "./graphqlProvider";
import Sidebar from "@/components/Sidebar";

const organizations = [
  { id: "1", name: "Marketing Team" },
  { id: "2", name: "Development Team" },
  { id: "3", name: "Sales Team" },
  { id: "4", name: "HR Department" },
  { id: "5", name: "Design Team" }
];


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Opentask",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <GraphQlProviders>
            <div className="flex">
              
              <div className="fixed inset-y-0 left-0 w-64">
                <Sidebar organizations={organizations} />
              </div>

              
              <main className="ml-64 flex-1 p-6">
                {children}
              </main>
            </div>
          </GraphQlProviders>
        </Providers>

      </body>
    </html>
  );
}
